
server:
  port: 8180

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erzu78/knowstars_config.git
          search-paths: /
      label: master


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/