
server:
  port: 8088

spring:
  application:
    name: zy-consumer
  redis:
    host: 192.168.1.135
    port: 6379
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



  #feign:
  # hystrix:
  #  enabled: false