
server:
  port: 8088

spring:
  application:
    name: zy-consumer
  redis:
    host: localhost
    port: 6379
    #password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



  #feign:
  # hystrix:
  #  enabled: false