server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: userinfo-consumer
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300
feign:
  hystrix:
    enabled: false
