
server:
  port: 8013

spring:
  application:
    name: information_consumer
  redis:
      host: 192.168.1.111
      port: 6379
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



feign:
  hystrix:
    enabled: false
