
server:
  port: 8013

spring:
  application:
    name: information_consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


feign:
  hystrix:
    enabled: false
