server:
  port: 8000
spring:
  application:
    name: likecomment-consumer
  redis:
    host: 192.168.1.148
    port: 6379
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: false