server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: homepage-provider
  datasource:
      url: jdbc:mysql://192.168.1.139:3306/knowstars78?useUnicode=true&characterEncoding=utf-8
    username: erzhu
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapping/*.xml